#!/usr/bin/env bash
# Course assembly pipeline for sota-present
# Assembles modules into a single HTML course

set -e

MODULES_DIR=${1:?Usage: build-course.sh <modules-dir> <style-id> [output-dir]}
STYLE_ID=${2:?Missing style ID}
OUTPUT_DIR=${3:-output/course}

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

echo "📚 Building course..."
echo "  Modules: $MODULES_DIR"
echo "  Style: $STYLE_ID"
echo "  Output: $OUTPUT_DIR"
echo ""

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Check if modules exist
if [ ! -d "$MODULES_DIR" ] || [ -z "$(ls -A "$MODULES_DIR"/module-*.html 2>/dev/null)" ]; then
  echo "❌ No modules found in $MODULES_DIR"
  echo "   Expected files: module-01.html, module-02.html, etc."
  exit 1
fi

# Extract tokens
echo "📋 Extracting design tokens..."
python3 << EOF
import json, sys

with open('$SCRIPT_DIR/catalog/styles.json', 'r') as f:
    styles = json.load(f)

style = next((s for s in styles['styles'] if s['id'] == '$STYLE_ID'), None)
if not style:
    print(f"❌ Style not found: $STYLE_ID")
    sys.exit(1)

tokens = style['tokens']
print(f"✅ Found style: {style['name']}")

# Output tokens as CSS custom properties
css = ":root {\n"
for key, value in tokens.items():
    css += f"  --{key.replace('_', '-')}: {value};\n"
css += "}\n"

with open('$OUTPUT_DIR/tokens.css', 'w') as f:
    f.write(css)

print(f"✅ Tokens written to $OUTPUT_DIR/tokens.css")
EOF

# Assemble HTML
echo ""
echo "🔨 Assembling course HTML..."

cat > "$OUTPUT_DIR/index.html" << 'HEADER'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Codebase Course — Generated by sota-present</title>

  <!-- Google Fonts (customize based on style) -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">

  <style>
HEADER

# Add tokens
cat "$OUTPUT_DIR/tokens.css" >> "$OUTPUT_DIR/index.html"

# Add base styles (placeholder - will be replaced with actual styles.css)
cat >> "$OUTPUT_DIR/index.html" << 'STYLES'

    /* Base course styles */
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: var(--font-body);
      background: var(--color-bg);
      color: var(--color-text);
      line-height: 1.6;
    }

    .course-nav {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      height: 60px;
      background: var(--color-surface);
      border-bottom: 1px solid var(--color-border);
      z-index: 1000;
      display: flex;
      align-items: center;
      padding: 0 20px;
    }

    .progress-bar {
      position: absolute;
      bottom: 0;
      left: 0;
      height: 3px;
      background: var(--color-primary);
      width: 0%;
      transition: width 0.3s ease;
    }

    .course-main {
      margin-top: 60px;
      scroll-snap-type: y mandatory;
      overflow-y: scroll;
      height: calc(100vh - 60px);
    }

    .module {
      min-height: calc(100vh - 60px);
      scroll-snap-align: start;
      padding: 80px 40px;
      display: flex;
      flex-direction: column;
      justify-content: center;
    }

    .module h1 {
      font-family: var(--font-heading);
      font-size: 3rem;
      margin-bottom: 2rem;
      color: var(--color-primary);
    }

    .module h2 {
      font-family: var(--font-heading);
      font-size: 2rem;
      margin-bottom: 1.5rem;
    }

    .module p {
      font-size: 1.125rem;
      margin-bottom: 1rem;
      max-width: 800px;
    }

    pre {
      background: var(--color-surface);
      border: 1px solid var(--color-border);
      border-radius: var(--radius-md);
      padding: 20px;
      overflow-x: auto;
      margin: 1rem 0;
    }

    code {
      font-family: var(--font-mono);
      font-size: 0.875rem;
    }

    /* Interactive elements will be styled by main.js CSS */
STYLES

cat >> "$OUTPUT_DIR/index.html" << 'MIDDLE'
  </style>
</head>
<body>
  <nav class="course-nav">
    <div class="progress-bar" id="progress-bar"></div>
    <div>Codebase Course</div>
  </nav>

  <main class="course-main">
MIDDLE

# Add modules
for module in "$MODULES_DIR"/module-*.html; do
  echo "  Adding: $(basename "$module")"
  cat "$module" >> "$OUTPUT_DIR/index.html"
done

# Close HTML and add JS
cat >> "$OUTPUT_DIR/index.html" << 'FOOTER'
  </main>

  <footer class="course-footer">
    <p>Generated by sota-present from codebase analysis</p>
  </footer>

  <script>
    // Base course JavaScript
    // Progress bar
    const progressBar = document.getElementById('progress-bar');
    const courseMain = document.querySelector('.course-main');

    courseMain.addEventListener('scroll', () => {
      const scrolled = courseMain.scrollTop;
      const total = courseMain.scrollHeight - courseMain.clientHeight;
      const percent = (scrolled / total) * 100;
      progressBar.style.width = percent + '%';
    });

    // Keyboard navigation
    document.addEventListener('keydown', (e) => {
      const modules = document.querySelectorAll('.module');
      const current = Math.round(courseMain.scrollTop / (window.innerHeight - 60));

      if (e.key === 'ArrowDown' || e.key === 'PageDown') {
        e.preventDefault();
        const next = Math.min(current + 1, modules.length - 1);
        modules[next].scrollIntoView({ behavior: 'smooth' });
      } else if (e.key === 'ArrowUp' || e.key === 'PageUp') {
        e.preventDefault();
        const prev = Math.max(current - 1, 0);
        modules[prev].scrollIntoView({ behavior: 'smooth' });
      }
    });

    // Interactive elements will be initialized by main.js
  </script>
</body>
</html>
FOOTER

echo ""
echo "✅ Course assembled: $OUTPUT_DIR/index.html"
echo "   Open in browser to view."
